let xn: number;
let xb: boolean;
let xs: string;
let a: number = 1;
let b: boolean = false;
let c: string = "string content";
let d = 1;
let e = false;
let f = "string content";
const g: number = 1;
const h: boolean = false;
const i: string = "string content";
const j = 1;
const k = false;
const l = "string content";

ss_assert(xn == 0);
ss_assert(xb == false);
ss_assert(xs == "");
ss_assert(a == 1);
ss_assert(b == false);
ss_assert(c == "string content");
ss_assert(d == 1);
ss_assert(e == false);
ss_assert(f == "string content");
ss_assert(g == 1);
ss_assert(h == false);
ss_assert(i == "string content");
ss_assert(j == 1);
ss_assert(k == false);
ss_assert(l == "string content");