let x;
const y;
let xn: number;
let xb: boolean;
let xs: string;
const yn: number;
const yb: boolean;
const ys: string;
let a: number = 1;
let b: boolean = false;
let c: string = "string content";
let d = 1;
let e = false;
let f = "string content";
const g: number = 1;
const h: boolean = false;
const i: string = "string content";
const j = 1;
const k = false;
const l = "string content";